export enum ActaKeys {
    SPEC_INFOS = 'SPEC_INFOS',
    SPEC_GLOBAL = 'SPEC_GLOBAL',
    SPEC_SERVICES = 'SPEC_SERVICES',

    SOURCE_URL = 'SOURCE_URL',
    SOURCE_LOADING = 'SOURCE_LOADING',
    SOURCE_LAODING_ERROR = 'SOURCE_LAODING_ERROR',

    GLOBAL_FORM = 'GLOBAL_FORM',
}