site_name: Athena
site_url: https://example.com
repo_url: https://github.com/fabien-h/athena
repo_name: fabien-h/athena
edit_uri: edit/main/docs/
plugins:
  - search
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    code: IBM Plex Mono
    text: IBM Plex Sans
  features:
    - content.action.edit
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - toc.integrate
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-night
        name: dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: dark

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fabien-h
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabien_huet
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fabien-h/

copyright: Let's build APIs.
