[package]
edition = "2021"
name = "athena-cli"
version = "0.1.0"

[dependencies]
athena-core = {path = "../athena-core"}
clap = {version = "4.5.4", features = ["derive"]}
tokio = {version = "1.37.0", features = ["full"]}
